version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    working_dir: /project
    volumes:
      - .:/project
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "90:80"
    depends_on:
      - php
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /project
    depends_on:
      - database
    volumes:
      - .:/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: fellowship
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: developer
    ports:
      - "5433:5432"
    volumes:
      - ./docker/db:/dump
      - ./docker/pgsqldata:/var/lib/postgresql
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
    driver: bridge