version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    working_dir: /project
    volumes:
      - .:/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "90:80"
    depends_on:
      - php
    networks:
      - symfony

  php:
    image: php:8.2-fpm
    container_name: symfony_php
    working_dir: /project
    volumes:
      - .:/project
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - symfony

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: fellowship
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
    driver: bridge